{
 "title": "graphs.skowronski.cloud",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "c10_bedroom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bedroom Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Bedroom",
     "select": [
      [
       { "params": [ "temperature_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bedroom CO2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Bedroom",
     "select": [
      [
       { "params": [ "co2_ppm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bedroom Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Bedroom",
     "select": [
      [
       { "params": [ "humidity_perc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bedroom Environment",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Bedroom",
     "select": [
      [
       { "params": [ "temperature_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Bedroom",
     "select": [
      [
       { "params": [ "humidity_perc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bedroom Air",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "alias": "CO2",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Bedroom",
     "select": [
      [
       { "params": [ "co2_ppm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Formaldehyde",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Bedroom",
     "select": [
      [
       { "params": [ "formaldehyde_ppm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "VOC",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Bedroom",
     "select": [
      [
       { "params": [ "voc_ppm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "c10_outside", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Outside Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "feinstaub",
     "select": [
      [
       { "params": [ "BME280_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outside Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "feinstaub",
     "select": [
      [
       { "params": [ "BME280_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outside Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "feinstaub",
     "select": [
      [
       { "params": [ "BME280_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outside PM10",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "feinstaub",
     "select": [
      [
       { "params": [ "SDS_P1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outside Environment",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "feinstaub",
     "select": [
      [
       { "params": [ "BME280_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "feinstaub",
     "select": [
      [
       { "params": [ "BME280_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outside Pollution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "alias": "PM10",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "feinstaub",
     "select": [
      [
       { "params": [ "SDS_P1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PM2.5",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "feinstaub",
     "select": [
      [
       { "params": [ "SDS_P2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outside Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "alias": "pressure",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "feinstaub",
     "select": [
      [
       { "params": [ "BME280_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "temperature",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "feinstaub",
     "select": [
      [
       { "params": [ "BME280_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "c10_study", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Study Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Study",
     "select": [
      [
       { "params": [ "temperature_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Study CO2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Study",
     "select": [
      [
       { "params": [ "co2_ppm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Study Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Study",
     "select": [
      [
       { "params": [ "humidity_perc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Study Environment",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Study",
     "select": [
      [
       { "params": [ "temperature_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Study",
     "select": [
      [
       { "params": [ "humidity_perc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Study Air",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "alias": "CO2",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Study",
     "select": [
      [
       { "params": [ "co2_ppm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Formaldehyde",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Study",
     "select": [
      [
       { "params": [ "formaldehyde_ppm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "VOC",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SmartAirBox_Study",
     "select": [
      [
       { "params": [ "voc_ppm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}